#!/bin/bash
# Exit script if any command returns non-zero
set -e
set -o pipefail
cargo build --target wasm32-unknown-unknown --release
wasm-bindgen target/wasm32-unknown-unknown/release/wasm_bindgen_file_reader_test.wasm --out-dir static/ --target no-modules

# Add glue code to make loader generated by wasm_bindgen compatible with the previous one that was
# generated by cargo-web
cat << EOF >> static/wasm_bindgen_file_reader_test.js
let Rust = {};
Rust.wasm_bindgen_file_reader_test = wasm_bindgen(
    "./wasm_bindgen_file_reader_test_bg.wasm"
).then(
    function(unused) {
        return wasm_bindgen;
    },
    function(err) {
        console.error(err);
    }
);
EOF

# Generate local documentation
#cargo doc --features="main"
#cp -rf target/doc target/deploy/doc
